[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6"
# runner = "espflash flash --monitor -L defmt"


[build]
rustflags = [
    "-C",
    "link-arg=-Tlinkall.x",

    # Add `defmt`linking options
    "-C",
    "link-arg=-Tdefmt.x",

    # Required to obtain backtraces (e.g. when using the "esp-backtrace" crate.)
    # NOTE: May negatively impact performance of produced code
    "-C",
    "force-frame-pointers",
]

target = "riscv32imac-unknown-none-elf"

[unstable]
build-std = ["core"]

[env]
DEFMT_LOG = "trace"
ESP_LOG = "trace"
