[package]
edition = "2021"
name = "blinky-lp"
version = "0.1.0"

[[bin]]
name = "blinky-lp"
path = "./src/bin/main.rs"

[dependencies]
embedded-hal = "1.0.0"
esp-lp-hal = { version = "0.1.0", features = ["esp32c6"] }
panic-halt = "1.0.0"

[build-dependencies]
esp-build = { version = "0.2.0" }


[profile.dev]
# Rust debug is too slow.
# For debug builds always builds with some optimization
opt-level = "s"

[profile.release]
codegen-units = 1        # LLVM can perform better optimizations using a single thread
debug = 2
debug-assertions = false
incremental = false
lto = 'fat'
opt-level = 's'
overflow-checks = false
