[target.riscv32imac-unknown-none-elf]
runner = "probe-rs run --chip=esp32c6"

[env]
DEFMT_LOG = "info"


[build]
# target = "riscv32imc-unknown-none-elf"  # ESP32-S2 + ESP32-S3
target = "riscv32imac-unknown-none-elf" # ESP32-C6

[target.'cfg(target_arch = "riscv32")']
rustflags = ["-C", "link-arg=-Tlink.x"]


[unstable]
build-std = ["core"]
